In [7]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118

You should consider upgrading via the 'C:\Users\Admin\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [1]:
!pip install gym[box2d] pyglet

You should consider upgrading via the 'C:\Users\Admin\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


# Import

In [1]:
import os
import time
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

# Environment

In [2]:
environment_name = 'CarRacing-v0'
env = gym.make(environment_name)

In [3]:
env.reset()

Track generation: 1175..1475 -> 300-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1025..1286 -> 261-tiles track


C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [4]:
env.close()

In [8]:
env.action_space

Box([-1.  0.  0.], [1. 1. 1.], (3,), float32)

In [9]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [10]:
env.render()

True

In [11]:
env.close()

In [4]:
episode = 5
# fps = 30
for episode in range(1, episode+1):
    obs = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        # time.sleep(1 / fps)
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        score += reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

Track generation: 1082..1357 -> 275-tiles track


C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


Episode:1 Score:-27.00729927007331
Track generation: 1068..1339 -> 271-tiles track
Episode:2 Score:-25.925925925926176
Track generation: 1057..1325 -> 268-tiles track
Episode:3 Score:-25.093632958801702
Track generation: 1101..1381 -> 280-tiles track
Episode:4 Score:-28.31541218638026
Track generation: 1007..1263 -> 256-tiles track
Episode:5 Score:-21.568627450980376


# Training Model

In [3]:
env = gym.make(environment_name)
env= DummyVecEnv([lambda : env])

In [4]:
log_path = os.path.join('Training', 'Logs')
log_path

'Training\\Logs'

In [5]:
model = PPO('MlpPolicy', env, verbose = 1, tensorboard_log=log_path)

Using cpu device
Wrapping the env in a VecTransposeImage.


In [7]:
PPO??

In [6]:
model.learn(total_timesteps=2000000)

Track generation: 1028..1289 -> 261-tiles track


C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


Logging to Training\Logs\PPO_2
Track generation: 1042..1313 -> 271-tiles track
Track generation: 1092..1369 -> 277-tiles track
-----------------------------
| time/              |      |
|    fps             | 158  |
|    iterations      | 1    |
|    time_elapsed    | 12   |
|    total_timesteps | 2048 |
-----------------------------
Track generation: 1161..1456 -> 295-tiles track
Track generation: 1152..1444 -> 292-tiles track
-----------------------------------------
| time/                   |             |
|    fps                  | 82          |
|    iterations           | 2           |
|    time_elapsed         | 49          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.003477924 |
|    clip_fraction        | 0.0449      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.25       |
|    explained_variance   | -0.0237     |
|    learning_rate        | 0.0003      |
|    loss            

KeyboardInterrupt: 

# Save Model

In [9]:
PPO_Path = os.path.join('Training', 'Logs', 'PPO_2m_Driving_model')

In [10]:
model.save(PPO_Path)

C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\stable_baselines3\common\save_util.py:278: UserWarning: Path 'Training\Saved_Models' does not exist. Will create it.
  warnings.warn(f"Path '{path.parent}' does not exist. Will create it.")


In [10]:
model = PPO.load(PPO_Path, env=env)

FileNotFoundError: [Errno 2] No such file or directory: 'Training\\Logs\\PPO_2m_Driving_model.zip'

# Evaluate

In [14]:
evaluate_policy(model, env, n_eval_episodes=10,render=True)

C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\stable_baselines3\common\evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Track generation: 1188..1489 -> 301-tiles track
Track generation: 1232..1544 -> 312-tiles track
Track generation: 1115..1398 -> 283-tiles track
Track generation: 1057..1330 -> 273-tiles track
Track generation: 1040..1304 -> 264-tiles track
Track generation: 1272..1594 -> 322-tiles track
Track generation: 1259..1578 -> 319-tiles track
Track generation: 1193..1495 -> 302-tiles track
Track generation: 1085..1368 -> 283-tiles track
Track generation: 1067..1338 -> 271-tiles track
Track generation: 1069..1348 -> 279-tiles track


(-62.153841736912725, 2.574022395414857)

In [15]:
env.close()

In [11]:
PPO_Path = os.path.join('Training', 'Saved_Models', 'PPO_2m_Driving_model')

In [12]:
model = PPO.load(PPO_Path, env=env)

C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object lr_schedule. Consider using `custom_objects` argument to replace this object.
Exception: an integer is required (got type bytes)
  warnings.warn(
C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object clip_range. Consider using `custom_objects` argument to replace this object.
Exception: an integer is required (got type bytes)
  warnings.warn(


Wrapping the env in a VecTransposeImage.


C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\stable_baselines3\common\base_class.py:728: UserWarning: You are probably loading a model saved with SB3 < 1.7.0, we deactivated exact_match so you can save the model again to avoid issues in the future (see https://github.com/DLR-RM/stable-baselines3/issues/1233 for more info). Original error: Error(s) in loading state_dict for ActorCriticCnnPolicy:
	Missing key(s) in state_dict: "pi_features_extractor.cnn.0.weight", "pi_features_extractor.cnn.0.bias", "pi_features_extractor.cnn.2.weight", "pi_features_extractor.cnn.2.bias", "pi_features_extractor.cnn.4.weight", "pi_features_extractor.cnn.4.bias", "pi_features_extractor.linear.0.weight", "pi_features_extractor.linear.0.bias", "vf_features_extractor.cnn.0.weight", "vf_features_extractor.cnn.0.bias", "vf_features_extractor.cnn.2.weight", "vf_features_extractor.cnn.2.bias", "vf_features_extractor.cnn.4.weight", "vf_features_extractor.cnn.4.bias", "vf_features_extract

In [13]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\stable_baselines3\common\evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Track generation: 1240..1554 -> 314-tiles track


C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


Track generation: 1347..1688 -> 341-tiles track
Track generation: 1090..1368 -> 278-tiles track
Track generation: 1147..1438 -> 291-tiles track
Track generation: 1152..1444 -> 292-tiles track
Track generation: 1215..1523 -> 308-tiles track
Track generation: 1071..1343 -> 272-tiles track
Track generation: 1087..1367 -> 280-tiles track
Track generation: 1099..1378 -> 279-tiles track
Track generation: 943..1187 -> 244-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1115..1398 -> 283-tiles track
Track generation: 1146..1444 -> 298-tiles track


(702.7882888264954, 155.6628115053333)

In [14]:
env.close()

In [20]:
episodes = 5
for episode in range(1, episodes+1):
    obs = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        action,_ = model.predict(obs) #using model
        obs, reward, done, info = env.step(action)
        score += reward
    print('Episode: {} Score: {}'.format(episode,score))
env.close()

Track generation: 1260..1579 -> 319-tiles track
Track generation: 1151..1443 -> 292-tiles track
Episode: 1 Score: [610.6909]
Track generation: 1017..1275 -> 258-tiles track
Track generation: 1119..1406 -> 287-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1120..1414 -> 294-tiles track
Episode: 2 Score: [732.694]
Track generation: 950..1200 -> 250-tiles track
Track generation: 1232..1544 -> 312-tiles track
Episode: 3 Score: [775.51324]
Track generation: 1214..1521 -> 307-tiles track
Track generation: 1128..1416 -> 288-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 927..1170 -> 243-tiles track
Episode: 4 Score: [671.2471]
Track generation: 1058..1330 -> 272-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1125..1418 -> 293-tiles track
Track generation: 1123..1408 -> 285-tiles track
Episode: 5 Score: [725