In [13]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118


You should consider upgrading via the 'C:\Users\Admin\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [9]:
import gym
import time
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env
import os

# Test Environment

In [15]:
!python -m atari_py.import_roms .\ROMS

copying adventure.bin from .\ROMS\Adventure (1980) (Atari, Warren Robinett) (CX2613, CX2613P) (PAL).bin to C:\Users\Admin\anaconda3\lib\site-packages\atari_py\atari_roms\adventure.bin
copying air_raid.bin from .\ROMS\Air Raid (1982) (Men-A-Vision) (PAL) ~.bin to C:\Users\Admin\anaconda3\lib\site-packages\atari_py\atari_roms\air_raid.bin
copying alien.bin from .\ROMS\Alien (1982) (20th Century Fox Video Games, Douglas 'Dallas North' Neubauer) (11006) ~.bin to C:\Users\Admin\anaconda3\lib\site-packages\atari_py\atari_roms\alien.bin
copying amidar.bin from .\ROMS\Amidar (1982) (Parker Brothers, Ed Temple) (PB5310) ~.bin to C:\Users\Admin\anaconda3\lib\site-packages\atari_py\atari_roms\amidar.bin
copying assault.bin from .\ROMS\Assault (AKA Sky Alien) (1983) (Bomb - Onbase) (CA281).bin to C:\Users\Admin\anaconda3\lib\site-packages\atari_py\atari_roms\assault.bin
copying asterix.bin from .\ROMS\Asterix (AKA Taz) (1984) (Atari, Jerome Domurat, Steve Woita) (CX2696).bin to C:\Users\Admin\anac

In [10]:
environment_name = 'Breakout-v0'
env = gym.make(environment_name)

In [17]:
env.reset()

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [18]:
env.action_space

Discrete(4)

In [20]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [4]:
episode = 5
fps = 30
for episode in range(1, episode+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        time.sleep(1 / fps)
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        score += reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\gym\envs\atari\environment.py:267: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  logger.warn(
C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


Episode:1 Score:0.0
Episode:2 Score:4.0
Episode:3 Score:0.0
Episode:4 Score:2.0
Episode:5 Score:1.0


# Vectorise Environment and Train Model

In [3]:
env = make_atari_env('Breakout-v0', n_envs=4, seed=0)
env = VecFrameStack(env,n_stack=4)

In [4]:
log_path = os.path.join('Training', 'Logs')
model = A2C('CnnPolicy',env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env in a VecTransposeImage.


In [6]:
model.learn(total_timesteps=2000000)

Logging to Training\Logs\A2C_2
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 755      |
|    ep_rew_mean        | 12       |
| time/                 |          |
|    fps                | 248      |
|    iterations         | 100      |
|    time_elapsed       | 8        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -0.111   |
|    explained_variance | 0.754    |
|    learning_rate      | 0.0007   |
|    n_updates          | 48265    |
|    policy_loss        | -0.0826  |
|    value_loss         | 0.427    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 680      |
|    ep_rew_mean        | 10.6     |
| time/                 |          |
|    fps                | 235      |
|    iterations         | 200      |
|    time_elapsed       | 16       |
|    total_timesteps    | 4000     |
| train

# Save and Reload Model

In [24]:
a2c_path = os.path.join('Training', 'Saved Models', 'A2C_Breakout')
model.save(a2c_path)

C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\stable_baselines3\common\save_util.py:278: UserWarning: Path 'Training\Saved Models' does not exist. Will create it.
  warnings.warn(f"Path '{path.parent}' does not exist. Will create it.")


In [25]:
del model

In [26]:
model = A2C.load(a2c_path, env)

Wrapping the env in a VecTransposeImage.


# Evaluate and Test

In [13]:
env = make_atari_env('Breakout-v0', n_envs=1, seed = 0)
env = VecFrameStack(env, n_stack=4)

In [28]:
evaluate_policy(model,env, n_eval_episodes=10, render=True)

C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\gym\envs\atari\environment.py:267: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  logger.warn(
C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


(7.0, 1.4142135623730951)

In [29]:
env.close()

In [14]:
a2c_path = os.path.join('Training', 'Saved Models', 'A2C_2M_model')

In [15]:
model = A2C.load(a2c_path, env)

Wrapping the env in a VecTransposeImage.


C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\stable_baselines3\common\base_class.py:728: UserWarning: You are probably loading a model saved with SB3 < 1.7.0, we deactivated exact_match so you can save the model again to avoid issues in the future (see https://github.com/DLR-RM/stable-baselines3/issues/1233 for more info). Original error: Error(s) in loading state_dict for ActorCriticCnnPolicy:
	Missing key(s) in state_dict: "pi_features_extractor.cnn.0.weight", "pi_features_extractor.cnn.0.bias", "pi_features_extractor.cnn.2.weight", "pi_features_extractor.cnn.2.bias", "pi_features_extractor.cnn.4.weight", "pi_features_extractor.cnn.4.bias", "pi_features_extractor.linear.0.weight", "pi_features_extractor.linear.0.bias", "vf_features_extractor.cnn.0.weight", "vf_features_extractor.cnn.0.bias", "vf_features_extractor.cnn.2.weight", "vf_features_extractor.cnn.2.bias", "vf_features_extractor.cnn.4.weight", "vf_features_extractor.cnn.4.bias", "vf_features_extract

In [9]:
fps = 30
episode = 10
for episode in range(1,episode+1):
    obs = env.reset()
    done = False
    score = 0
    while not done:
        env.render()
        # time.sleep(1/fps)
        action = model.predict(obs)
        action = action[0]
        obs, reward, done, info = env.step(action)
        score += reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

Episode:1 Score:[0.]
Episode:2 Score:[13.]
Episode:3 Score:[0.]
Episode:4 Score:[0.]
Episode:5 Score:[0.]
Episode:6 Score:[0.]
Episode:7 Score:[0.]
Episode:8 Score:[6.]
Episode:9 Score:[4.]
Episode:10 Score:[1.]


In [16]:
evaluate_policy(model,env, n_eval_episodes=10, render=True)

C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\gym\envs\atari\environment.py:267: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  logger.warn(
C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


(23.1, 9.782126558167198)

In [17]:
env.close()

In [11]:
del model

In [21]:
a2c_path = os.path.join('Training', 'Saved Models', 'A2C_2M_model')

In [22]:
model = A2C.load(a2c_path, env)

Wrapping the env in a VecTransposeImage.


In [23]:
evaluate_policy(model,env, n_eval_episodes=10, render=True)

(22.4, 7.578918128598566)

In [24]:
env.close()